version: "3"

services:
  web-frontend:
    build: .
    ports:
      - 8080:8080
    command: sh -c "npm install && npm rebuild node-sass && npm run serve"
    volumes:
      - ".:/app"
    environment:
      HOST: 0.0.0.0